import { CodingCodon, Protein, ProteinCode } from "@/types/dna/types";

export const PROTEINS = {
  A: {
    abbrevName: "Ala",
    charCode: "A",
    charge: "neutral",
    fullName: "Alanine",
    codons: ["GCT", "GCC", "GCA", "GCG"],
    chemicalFormula: "C3H7NO2",
    isEssential: false,
    isStartCodon: false,
    isStopCodon: false,
    description:
      "A nonpolar, aliphatic amino acid used in protein biosynthesis.",
  },
  R: {
    abbrevName: "Arg",
    charCode: "R",
    charge: "positive",
    fullName: "Arginine",
    codons: ["CGT", "CGC", "CGA", "CGG", "AGA", "AGG"],
    chemicalFormula: "C6H14N4O2",
    isEssential: "conditionally",
    essentialNotes: "essential in infants and certain disease states",
    isStartCodon: false,
    isStopCodon: false,
    description:
      "A positively charged, polar amino acid important for the immune system.",
    polar: true,
  },
  N: {
    abbrevName: "Asp",
    charCode: "N",
    charge: "neutral",
    fullName: "Asparagine",
    codons: ["AAT", "AAC"],
    chemicalFormula: "C4H8N2O3",
    isEssential: false,
    isStartCodon: false,
    isStopCodon: false,
    description:
      "A polar, uncharged amino acid that plays a role in the biosynthesis of glycoproteins.",
    polar: true,
  },
  D: {
    abbrevName: "AspD",
    charCode: "D",
    charge: "negative",
    fullName: "Aspartic acid",
    codons: ["GAT", "GAC"],
    chemicalFormula: "C4H7NO4",
    isEssential: false,
    isStartCodon: false,
    isStopCodon: false,
    description:
      "A negatively charged amino acid involved in the citric acid cycle.",
    polar: true,
  },
  C: {
    abbrevName: "Cys",
    charCode: "C",
    charge: "neutral/neg",
    chargeNotes: "can be negative if the thiol group is deprotonated",
    fullName: "Cysteine",
    codons: ["TGT", "TGC"],
    chemicalFormula: "C3H7NO2S",
    isEssential: "conditionally",
    isStartCodon: false,
    isStopCodon: false,
    description:
      "A semi-essential, sulfur-containing amino acid important for protein structure.",
    polar: true,
  },
  Q: {
    abbrevName: "Glu",
    charCode: "Q",
    charge: "neutral",
    fullName: "Glutamine",
    codons: ["CAA", "CAG"],
    chemicalFormula: "C5H10N2O3",
    isEssential: "conditionally",
    isStartCodon: false,
    isStopCodon: false,
    description:
      "A polar, uncharged amino acid involved in ammonia detoxification and immune function.",
    polar: true,
  },
  E: {
    abbrevName: "GluD",
    charCode: "E",
    charge: "negative",
    fullName: "Glutamic acid",
    codons: ["GAA", "GAG"],
    chemicalFormula: "C5H9NO4",
    isEssential: false,
    isStartCodon: false,
    isStopCodon: false,
    description:
      "A negatively charged, polar amino acid that plays a key role in cellular metabolism.",
    polar: true,
  },
  G: {
    abbrevName: "Gly",
    charCode: "G",
    charge: "neutral",
    fullName: "Glycine",
    codons: ["GGT", "GGC", "GGA", "GGG"],
    chemicalFormula: "C2H5NO2",
    isEssential: false,
    isStartCodon: false,
    isStopCodon: false,
    description:
      "The simplest possible amino acid, involved in the synthesis of proteins.",
  },
  H: {
    abbrevName: "His",
    charCode: "H",
    charge: "neutral/pos",
    chargeNotes:
      "can be positive under certain conditions, depending on its environment",
    fullName: "Histidine",
    codons: ["CAT", "CAC"],
    chemicalFormula: "C6H9N3O2",
    isEssential: true,
    isStartCodon: false,
    isStopCodon: false,
    description:
      "An essential amino acid that plays a role in growth and tissue repair.",
    polar: true,
  },
  I: {
    abbrevName: "Iso",
    charCode: "I",
    charge: "neutral",
    fullName: "Isoleucine",
    codons: ["ATT", "ATC", "ATA"],
    chemicalFormula: "C6H13NO2",
    isEssential: true,
    isStartCodon: false,
    isStopCodon: false,
    description:
      "An essential amino acid important for energy production and immune function.",
  },
  L: {
    abbrevName: "Leu",
    charCode: "L",
    charge: "neutral",
    fullName: "Leucine",
    codons: ["CTT", "CTC", "CTA", "CTG", "TTA", "TTG"],
    chemicalFormula: "C6H13NO2",
    isEssential: true,
    isStartCodon: false,
    isStopCodon: false,
    description:
      "An essential amino acid critical for protein synthesis and muscle repair.",
  },
  K: {
    abbrevName: "Lys",
    charCode: "K",
    charge: "positive",
    fullName: "Lysine",
    codons: ["AAA", "AAG"],
    chemicalFormula: "C6H14N2O2",
    isEssential: true,
    isStartCodon: false,
    isStopCodon: false,
    description:
      "An essential amino acid important for protein synthesis, hormone production, and calcium absorption.",
    polar: true,
  },
  M: {
    abbrevName: "Meth",
    charCode: "M",
    charge: "neutral",
    fullName: "Methionine",
    codons: ["ATG"],
    chemicalFormula: "C5H11NO2S",
    isEssential: true,
    isStartCodon: true,
    isStopCodon: false,
    description:
      "An essential amino acid that serves as the start codon for protein synthesis.",
  },
  F: {
    abbrevName: "Phen",
    charCode: "F",
    charge: "neutral",
    fullName: "Phenylalanine",
    codons: ["TTT", "TTC"],
    chemicalFormula: "C9H11NO2",
    isEssential: true,
    isStartCodon: false,
    isStopCodon: false,
    description:
      "An essential amino acid that can be converted into tyrosine, used in the biosynthesis of proteins.",
  },
  P: {
    abbrevName: "Pro",
    charCode: "P",
    charge: "neutral",
    fullName: "Proline",
    codons: ["CCT", "CCC", "CCA", "CCG"],
    chemicalFormula: "C5H9NO2",
    isEssential: "conditionally",
    isStartCodon: false,
    isStopCodon: false,
    description:
      "A non-essential amino acid that plays an important role in protein folding and structure.",
  },
  S: {
    abbrevName: "Ser",
    charCode: "S",
    charge: "neutral",
    fullName: "Serine",
    codons: ["TCT", "TCC", "TCA", "TCG", "AGT", "AGC"],
    chemicalFormula: "C3H7NO3",
    isEssential: false,
    isStartCodon: false,
    isStopCodon: false,
    description:
      "A non-essential amino acid involved in the biosynthesis of purines and pyrimidines.",
    polar: true,
  },
  T: {
    abbrevName: "Thr",
    charCode: "T",
    charge: "neutral",
    fullName: "Threonine",
    codons: ["ACT", "ACC", "ACA", "ACG"],
    chemicalFormula: "C4H9NO3",
    isStartCodon: false,
    isStopCodon: false,
    description:
      "An essential amino acid important for protein balance in the body.",
    polar: true,
  },
  W: {
    abbrevName: "Try",
    charCode: "W",
    charge: "neutral",
    fullName: "Tryptophan",
    codons: ["TGG"],
    chemicalFormula: "C11H12N2O2",
    isEssential: true,
    isStartCodon: false,
    isStopCodon: false,
    description:
      "An essential amino acid that the body uses to produce serotonin.",
  },
  Y: {
    abbrevName: "Tyr",
    charCode: "Y",
    charge: "neutral/neg",
    chargeNotes: "can be negative if the phenol group is deprotonated",
    fullName: "Tyrosine",
    codons: ["TAT", "TAC"],
    chemicalFormula: "C9H11NO3",
    isEssential: "conditionally",
    essentialNotes: "essential only if phenylalanine is deficient",
    isStartCodon: false,
    isStopCodon: false,
    description:
      "A non-essential amino acid important for the production of neurotransmitters.",
    polar: true,
  },
  V: {
    abbrevName: "Val",
    charCode: "V",
    charge: "neutral",
    fullName: "Valine",
    codons: ["GTT", "GTC", "GTA", "GTG"],
    chemicalFormula: "C5H11NO2",
    isEssential: true,
    isStartCodon: false,
    isStopCodon: false,
    description:
      "An essential amino acid important for muscle growth and tissue repair.",
  },
  "": {
    abbrevName: "STOP",
    charCode: "",
    fullName: "Stop codon",
    codons: ["TAA", "TAG", "TGA"],
    chemicalFormula: "",
    isStartCodon: false,
    isStopCodon: true,
    description: "Signals the end of protein synthesis.",
  },
} as Record<ProteinCode, Protein>;

export const CODONS_TO_AMINO_ACIDS = {
  GCT: "A",
  GCC: "A",
  GCA: "A",
  GCG: "A",
  CGT: "R",
  CGC: "R",
  CGA: "R",
  CGG: "R",
  AGA: "R",
  AGG: "R",
  AAT: "N",
  AAC: "N",
  GAT: "D",
  GAC: "D",
  TGT: "C",
  TGC: "C",
  CAA: "Q",
  CAG: "Q",
  GAA: "E",
  GAG: "E",
  GGT: "G",
  GGC: "G",
  GGA: "G",
  GGG: "G",
  CAT: "H",
  CAC: "H",
  ATT: "I",
  ATC: "I",
  ATA: "I",
  CTT: "L",
  CTC: "L",
  CTA: "L",
  CTG: "L",
  TTA: "L",
  TTG: "L",
  AAA: "K",
  AAG: "K",
  ATG: "M",
  TTT: "F",
  TTC: "F",
  CCT: "P",
  CCC: "P",
  CCA: "P",
  CCG: "P",
  TCT: "S",
  TCC: "S",
  TCA: "S",
  TCG: "S",
  AGT: "S",
  AGC: "S",
  ACT: "T",
  ACC: "T",
  ACA: "T",
  ACG: "T",
  TGG: "W",
  TAT: "Y",
  TAC: "Y",
  GTT: "V",
  GTC: "V",
  GTA: "V",
  GTG: "V",
  TAA: "",
  TAG: "",
  TGA: "",
} as Record<CodingCodon, ProteinCode>;
