import type * as React from "react";
import type { SxProps, Theme } from "@mui/material/styles";
import type { SubsectionPagerItem } from "@/components/portfolio/layout/subsection-pager/types";
import type { MediaCyclerItem } from "@/types/media/mediaCycler";

export type ArchitectureDiagramsSlideProps = {
  activeDiagramKey?: string;
  diagramPagerItems: SubsectionPagerItem[];
  diagramItems: MediaCyclerItem[];
  hasMultipleDiagrams?: boolean;
  onSelectDiagram: (key: string) => void;
  onPreviousDiagram: () => void;
  onNextDiagram: () => void;
  setSlideRef?: (node: HTMLElement | null) => void;
  rootId?: string;
  rootClassName?: string;
  rootSx?: SxProps<Theme>;
  panelClassName?: string;
  panelSx?: SxProps<Theme>;
  topRailSx?: SxProps<Theme>;
  contentSx?: SxProps<Theme>;
  hostClassName?: string;
  hostSx?: SxProps<Theme>;
  menuId?: string;
  previousAriaLabel?: string;
  nextAriaLabel?: string;
  selectorAriaLabel?: string;
  fallbackTitle?: React.ReactNode;
  emptyMessage?: React.ReactNode;
  selectedValueAsTitle?: boolean;
  selectedVisualSize?: number;
  mediaCyclerStackSx?: SxProps<Theme>;
  mediaCyclerShowChevronNavigation?: boolean;
  mediaCyclerLoopNavigation?: boolean;
  mediaCyclerAllowSwipe?: boolean;
  mediaCyclerNavigationControlSx?: SxProps<Theme>;
  mediaCyclerExpandControlSx?: SxProps<Theme>;
  suppressMediaHeading?: boolean;
  showCopyLinkButton?: boolean;
  onCopyLink?: () => void;
  copyLinkCopied?: boolean;
  copyLinkAriaLabel?: string;
};
