import { useShallow } from "zustand/react/shallow";
import { usePathForgerUiStore } from "@/app/pathforger/_hooks/usePathForgerUiStore";

export function usePathForgerPageUiState() {
  return usePathForgerUiStore(
    useShallow((state) => ({
      pitchModalOpen: state.pitchModalOpen,
      setPitchModalOpen: state.setPitchModalOpen,
      controlsModalOpen: state.controlsModalOpen,
      setControlsModalOpen: state.setControlsModalOpen,
      settingsModalOpen: state.settingsModalOpen,
      setSettingsModalOpen: state.setSettingsModalOpen,
      renderImageCallsModalOpen: state.renderImageCallsModalOpen,
      setRenderImageCallsModalOpen: state.setRenderImageCallsModalOpen,
      chapterModalOpen: state.chapterModalOpen,
      setChapterModalOpen: state.setChapterModalOpen,
      continueModalOpen: state.continueModalOpen,
      setContinueModalOpen: state.setContinueModalOpen,
      chapterOutcomeModalOpen: state.chapterOutcomeModalOpen,
      setChapterOutcomeModalOpen: state.setChapterOutcomeModalOpen,
      createStoryPanelOpen: state.createStoryPanelOpen,
      setCreateStoryPanelOpen: state.setCreateStoryPanelOpen,
      hasCreateStoryFormBeenShown: state.hasCreateStoryFormBeenShown,
      setHasCreateStoryFormBeenShown: state.setHasCreateStoryFormBeenShown,
      pathLedgerModalOpen: state.pathLedgerModalOpen,
      setPathLedgerModalOpen: state.setPathLedgerModalOpen,
      journeyTabValue: state.journeyTabValue,
      setJourneyTabValue: state.setJourneyTabValue,
      persistenceDialogOpen: state.persistenceDialogOpen,
      setPersistenceDialogOpen: state.setPersistenceDialogOpen,
      chapterModalReachedEnd: state.chapterModalReachedEnd,
      setChapterModalReachedEnd: state.setChapterModalReachedEnd,
      isRunning: state.isRunning,
      setIsRunning: state.setIsRunning,
      isGeneratingChapterImages: state.isGeneratingChapterImages,
      setIsGeneratingChapterImages: state.setIsGeneratingChapterImages,
      activeRunAction: state.activeRunAction,
      setActiveRunAction: state.setActiveRunAction,
      errorMessage: state.errorMessage,
      setErrorMessage: state.setErrorMessage,
      selectedBranch: state.selectedBranch,
      setSelectedBranch: state.setSelectedBranch,
      activeOptionBranch: state.activeOptionBranch,
      setActiveOptionBranch: state.setActiveOptionBranch,
      revealedOptionBranches: state.revealedOptionBranches,
      setRevealedOptionBranches: state.setRevealedOptionBranches,
      optionRevealTick: state.optionRevealTick,
      setOptionRevealTick: state.setOptionRevealTick,
      forgedOutcomes: state.forgedOutcomes,
      setForgedOutcomes: state.setForgedOutcomes,
      forgedOutcomeImages: state.forgedOutcomeImages,
      setForgedOutcomeImages: state.setForgedOutcomeImages,
      lastForgedLedgerTransition: state.lastForgedLedgerTransition,
      setLastForgedLedgerTransition: state.setLastForgedLedgerTransition,
      pipelineRunDiagnostics: state.pipelineRunDiagnostics,
      pushPipelineRunDiagnostics: state.pushPipelineRunDiagnostics,
    })),
  );
}
