import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://cdn.jsdelivr.net/npm/pathseg@1.2.1/pathseg.js"
          async
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/poly-decomp@0.3.0/build/decomp.min.js"
          async
        ></script>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
