"use client";

import { askOpenAI } from "@/utils/talentforge/utils";

/**
 * Generate a tailored resume based on a user's resume and a job description.
 *
 * @param resume - The original resume content in plain text or Markdown.
 * @param jobDescription - The job description to tailor the resume for.
 * @returns The tailored resume generated by the AI model.
 */
export async function generateTailoredResume({
  resume,
  jobDescription,
}: {
  resume: string;
  jobDescription: string;
}): Promise<string> {
  const context = `Resume:\n${resume}\n\nJob Description:\n${jobDescription}`;
  const system =
    "You rewrite resumes so they best match a job description. " +
    "Return the full revised resume in markdown format.";

  const response = await askOpenAI({
    context,
    user: "Create a tailored resume",
    system,
    returnFirstResponse: true,
    logMessagesToChatHistory: false,
    chatHistory: [],
  });

  return response?.message?.trim() || "";
}

/**
 * Generate a cover letter using a resume and job description.
 *
 * @param resume - The original resume content in plain text or Markdown.
 * @param jobDescription - The job description to tailor the cover letter for.
 * @returns The generated cover letter.
 */
export async function generateCoverLetter({
  resume,
  jobDescription,
}: {
  resume: string;
  jobDescription: string;
}): Promise<string> {
  const context = `Resume:\n${resume}\n\nJob Description:\n${jobDescription}`;
  const system =
    "You craft professional cover letters using the resume and job description provided." +
    " Return the complete cover letter in markdown format.";

  const response = await askOpenAI({
    context,
    user: "Write a cover letter",
    system,
    returnFirstResponse: true,
    logMessagesToChatHistory: false,
    chatHistory: [],
  });

  return response?.message?.trim() || "";
}
